/*
 * This file is generated by jOOQ.
 */
package scrapper.domains.jooq.tables.records;


import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import scrapper.domains.jooq.tables.Chat;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatRecord extends UpdatableRecordImpl<ChatRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CHAT.CHAT_ID</code>.
     */
    public void setChatId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>CHAT.CHAT_ID</code>.
     */
    @Nullable
    public Long getChatId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>CHAT.TG_CHAT_ID</code>.
     */
    public void setTgChatId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>CHAT.TG_CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getTgChatId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Chat.CHAT.CHAT_ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return Chat.CHAT.TG_CHAT_ID;
    }

    @Override
    @Nullable
    public Long component1() {
        return getChatId();
    }

    @Override
    @NotNull
    public Long component2() {
        return getTgChatId();
    }

    @Override
    @Nullable
    public Long value1() {
        return getChatId();
    }

    @Override
    @NotNull
    public Long value2() {
        return getTgChatId();
    }

    @Override
    @NotNull
    public ChatRecord value1(@Nullable Long value) {
        setChatId(value);
        return this;
    }

    @Override
    @NotNull
    public ChatRecord value2(@NotNull Long value) {
        setTgChatId(value);
        return this;
    }

    @Override
    @NotNull
    public ChatRecord values(@Nullable Long value1, @NotNull Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatRecord
     */
    public ChatRecord() {
        super(Chat.CHAT);
    }

    /**
     * Create a detached, initialised ChatRecord
     */
    @ConstructorProperties({ "chatId", "tgChatId" })
    public ChatRecord(@Nullable Long chatId, @NotNull Long tgChatId) {
        super(Chat.CHAT);

        setChatId(chatId);
        setTgChatId(tgChatId);
    }

    /**
     * Create a detached, initialised ChatRecord
     */
    public ChatRecord(scrapper.domains.jooq.tables.pojos.Chat value) {
        super(Chat.CHAT);

        if (value != null) {
            setChatId(value.getChatId());
            setTgChatId(value.getTgChatId());
        }
    }
}
