/*
 * This file is generated by jOOQ.
 */
package scrapper.domains.jooq;


import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import scrapper.domains.jooq.tables.Chat;
import scrapper.domains.jooq.tables.ChatLink;
import scrapper.domains.jooq.tables.Link;
import scrapper.domains.jooq.tables.records.ChatLinkRecord;
import scrapper.domains.jooq.tables.records.ChatRecord;
import scrapper.domains.jooq.tables.records.LinkRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1 = Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1"), new TableField[] { Chat.CHAT.TG_CHAT_ID }, true);
    public static final UniqueKey<ChatRecord> PK_CHAT_CHAT_ID = Internal.createUniqueKey(Chat.CHAT, DSL.name("PK_CHAT_CHAT_ID"), new TableField[] { Chat.CHAT.CHAT_ID }, true);
    public static final UniqueKey<ChatLinkRecord> CONSTRAINT_8 = Internal.createUniqueKey(ChatLink.CHAT_LINK, DSL.name("CONSTRAINT_8"), new TableField[] { ChatLink.CHAT_LINK.CHAT_ID, ChatLink.CHAT_LINK.LINK_ID }, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_2 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] { Link.LINK.URL }, true);
    public static final UniqueKey<LinkRecord> PK_LINK_LINK_ID = Internal.createUniqueKey(Link.LINK, DSL.name("PK_LINK_LINK_ID"), new TableField[] { Link.LINK.LINK_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChatLinkRecord, ChatRecord> CONSTRAINT_86 = Internal.createForeignKey(ChatLink.CHAT_LINK, DSL.name("CONSTRAINT_86"), new TableField[] { ChatLink.CHAT_LINK.CHAT_ID }, Keys.PK_CHAT_CHAT_ID, new TableField[] { Chat.CHAT.CHAT_ID }, true);
    public static final ForeignKey<ChatLinkRecord, LinkRecord> CONSTRAINT_868 = Internal.createForeignKey(ChatLink.CHAT_LINK, DSL.name("CONSTRAINT_868"), new TableField[] { ChatLink.CHAT_LINK.LINK_ID }, Keys.PK_LINK_LINK_ID, new TableField[] { Link.LINK.LINK_ID }, true);
}
