name: Build bot App

on:
  push:
    paths:
      - '.github/workflows/bot.yml'
      - 'bot/**'

jobs:
  build:
    name: Build bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: maven package bot
        run: mvn package -pl bot -am
